version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    mysql:
        image: mysql:5.7.27
        environment:
            - MYSQL_ROOT_PASSWORD=root

        volumes:
            - ./store_files:/var/lib/mysql-files         
            - ./store_files:/store_files_mysql/
            - ./store_files:/store_files_mysql2/
            - ./mysql.cnf:/etc/mysql/mysql.cnf #
            - ./my.cnf:/etc/mysql/my.cnf #
            - ./my.cnf:/usr/local/etc/my.cnf #
            - ./my.cnf:/usr/local/mysql/etc/my.cnf #
            - ./my.cnf:/usr/local/lib/mysql/my.cnf #
            - ./mysql.cnf:/usr/local/lib/mysql/etc/mysql.cnf #
            - ./my.cnf:/etc/alternatives/my.cnf #
 

    webserver:
        image: puckel/docker-airflow:1.10.9

        restart: always
        depends_on:
            - postgres
            - mysql

        environment:
            - INSTALL_MYSQL=y
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__SMTP__SMTP_HOST=smtp.ukr.net
            - AIRFLOW__SMTP__SMTP_USER=ldb_s@ukr.net
            - AIRFLOW__SMTP__SMTP_PASSWORD=T6HuwtF3dcvGx6XZ
            - AIRFLOW__SMTP__SMTP_PORT=465
            - AIRFLOW__SMTP__SMTP_MAIL_FROM=airflow
            

        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./store_files:/usr/local/airflow/store_files_airflow1
            - ./sql_files1:/usr/local/airflow/sql_files1
            - ./store_files:/usr/local/airflow/store_files_airflow2
            - ./store_files:/usr/local/airflow/store_files_airflow_transformed 
            - ./store_files:/usr/local/airflow/store_files_mysql2/
            - ./sql_files2:/usr/local/airflow/sql_files2
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins

        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    redis: 
            image: 'redis:3.2.7' 
